### ISSUE TITLE
Handling 'nan'

### ISSUE THREAD

**Issue by ghost** [mcchots/homebridge-mqtt-humidity#3]
undefined:1
nan
 ^

SyntaxError: Unexpected token a
    at Object.parse (native)
    at MqttClient.<anonymous> (/usr/local/lib/node_modules/homebridge-mqtt-humidity/index.js:43:17)
    at emitThree (events.js:97:13)
    at MqttClient.emit (events.js:175:7)
    at MqttClient._handlePublish (/usr/local/lib/node_modules/homebridge-mqtt-humidity/node_modules/mqtt/lib/client.js:792:12)
    at MqttClient._handlePacket (/usr/local/lib/node_modules/homebridge-mqtt-humidity/node_modules/mqtt/lib/client.js:282:12)
    at process (/usr/local/lib/node_modules/homebridge-mqtt-humidity/node_modules/mqtt/lib/client.js:238:12)
    at Writable.writable._write (/usr/local/lib/node_modules/homebridge-mqtt-humidity/node_modules/mqtt/lib/client.js:248:5)
    at doWrite (/usr/local/lib/node_modules/homebridge-mqtt-humidity/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/local/lib/node_modules/homebridge-mqtt-humidity/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:227:5)

**Comment by mcchots** [comment]
Add some basic error handling c5d4fb9b509d9f7ff1abc23bde0052d1b8f532d3

**Comment by mcchots** [comment]
The latest release should not crash with NaN errors in the MQTT payload. Please try it out and let me know if it works.
